# Generated by Django 3.2.12 on 2022-04-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0002_auto_20220409_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showlist',
            options={'verbose_name': 'Show List', 'verbose_name_plural': 'Show Lists'},
        ),
        migrations.AlterModelOptions(
            name='streamplatform',
            options={'verbose_name': 'Stream Platform', 'verbose_name_plural': 'Stream Platforms'},
        ),
    ]
