# Generated by Django 3.2.12 on 2022-04-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0003_auto_20220409_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='showlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='show_list', to='showlist.streamplatform'),
            preserve_default=False,
        ),
    ]
