# Generated by Django 3.2.12 on 2022-04-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0006_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='review_user',
        ),
    ]
