# Generated by Django 3.2.12 on 2022-04-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0007_rename_author_review_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_user',
            new_name='author',
        ),
    ]
