# Generated by Django 3.2.12 on 2022-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0009_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='showlist',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='showlist',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
